### PR TITLE
ECM-218: Implements HATEOAS in REST request Backend Supplier Simulator

### PR DESCRIPTION
**Pull request by agallegoc**

### CODE REVIEW

**Comment by agallegoc** [comment]
Hi Lars, 
Let's go through the different points:
1. I don't get this:  did you create the links in the resources?
2. I will try to modify the code from List to map
3. The way in which I added the links to the results it was creating a Link Object with **Mongoose**, and it seems it automatically added this id. 
4. You mean something like : "href":"https://educama-supplier-simulator-backend-sandbox.mybluemix.net/api/airlineBooking/**undefined**/confirm? This is a problem with old data not containing the proper booking.

**Comment by larsduelfer** [comment]
Hi Alberto

1) No, this was just to describe which "links" I was referring to. All good!

2) Cool ;-)

3) Ok, doesn't hurt, let us leave it as is for now

4) Understood, maybe we should just delete the old data from the DB.

Regards, Lars

**Comment by agallegoc** [comment]
Hi Lars
I have made some modifications according to your comments.
Please take a look the result at:
https://educama-supplier-simulator-backend-sandbox.mybluemix.net/api/bookings
Hope it fits your expectations :)
Shönes Wochenande.
Alberto

**Comment by agallegoc** [comment]
Hi Lars
you got it!!
Have a nice day,
Alberto

**Comment by agallegoc** [comment]
Hi Lars
If you take a look at:
https://github.com/Educama/Showcase/blob/master/services/educama-supplier-simulator-backend/app/config.js
you can see that the **appURL** variable  contains the base url used to build each of the links.
As you can see here, this URL is gotten from the environment except in the case of running the app locally when this url is not available the way in which it is done in pcf.

**Comment by larsduelfer** [comment]
I Alberto, I integrated the PR. However, I would appreciate if you can have a look into it since it the links are not entirely "correct". Even when on the PCF on Bluemix the protocol of the links is always https and not the same one as used in the request. Would just be interesting to know, why that is. Regards, Lars

**Pull request merged**
